name: qbox_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  fluttertoast: ^8.0.9
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  cloud_firestore: ^3.1.18
  firebase_core_web: ^1.6.5
  flick_video_player: ^0.5.0
  video_player_web: ^2.0.10
  video_player: ^2.4.5
  chewie: ^1.3.4
  file_picker: ^4.6.0 
  intl: ^0.17.0
  firebase_messaging_web: ^3.1.0
  webviewx: ^0.2.1
  html_editor_enhanced: ^2.5.0
  flutter_tex: ^4.0.3+1
  math_keyboard: ^0.1.7
  syncfusion_flutter_xlsio: ^20.2.44-beta
  path_provider: ^2.0.11
  open_file: ^3.2.1
  universal_html: ^2.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
